# Generated by Django 4.0.6 on 2022-08-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike', to='app1.users'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='app1.users'),
        ),
    ]
