# Generated by Django 4.0.6 on 2022-08-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_video_dislike_alter_video_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
